/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { BooleanFilter } from "../../util/BooleanFilter";
import { MenuCategoryListRelationFilter } from "../../menuCategory/base/MenuCategoryListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { SizeListRelationFilter } from "../../size/base/SizeListRelationFilter";

@InputType()
class MenuItemWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  isOutOfStock?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: () => MenuCategoryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MenuCategoryListRelationFilter)
  @IsOptional()
  @Field(() => MenuCategoryListRelationFilter, {
    nullable: true,
  })
  menuCategories?: MenuCategoryListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  price?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SizeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SizeListRelationFilter)
  @IsOptional()
  @Field(() => SizeListRelationFilter, {
    nullable: true,
  })
  sizes?: SizeListRelationFilter;
}

export { MenuItemWhereInput as MenuItemWhereInput };
